### PR TITLE
Added Potential Tile Bonus System

### PR DESCRIPTION
**Pull request by theTreeSerok**
Also moved 'Tiles' section to above 'Turn Actions'.

### CODE REVIEW

**Comment by theTreeSerok** [comment]
Things to think about: 
Ways to denote a bonus has been exhausted (so as to minimize things to put in player memory), i.e., is the bonus icon ON the card? Is it some token randomly placed? 

How many of each bonus should there be? -> Balancing to be done -> Updating the rules section accordingly to fill in these gaps, they are just blank right now because I know not the best way without some testing, probably.

**Comment by theTreeSerok** [comment]
Ideally this will encourage players to explore the map, incentivize, as well as add some mechanics, most notably gaining units during play, but also provide (some more powerful than others) effects to make for more dynamic moments. Also having another physical element (cards) is kinda neat imo.

**Comment by BenjaFriend** [comment]
Card based system for tile bonuses looks 👌 
I think the bonus cards could use some revising though. (e.g. rolling die for combat). We should brainstorm to come up with more bonus types

**Comment by BenjaFriend** [comment]
I like the concept of superior position, but I do not like the dice roll. I also feel like that could make the numbers a bit high for combat. Possibly just add a +1 or +2 modifier on the tile

Artillery strike is also a good one, but we need to make sure that the artillary isn't super OP. Make it more like deal 2 damage to any unit on the baord, so that people can't just use their mechs to completely destroy someones infantry and have the other player feel like they can't do anything about it 

A question for 'Reinforcements' - Would this be it's own squad then? Do you need to go back to collect them and put them into your squad? Without squad splitting this is something we need to decide.

---
Possible new ability

| Bonus | Effect   |   
|---|---|
| Extra Ammo  | You can attack twice in a row with this unit from this tile *once*  |

**Comment by magnoahlia** [comment]
I really like the Extra Ammo idea! Stragglers/extra units is a great bonus, as is Fortifications. I'm a little weary of giving an entire extra squad with Reinforcements. I like @bah8892's idea of making it Artillery fixed damage, that makes more sense,

**Comment by BenjaFriend** [comment]
Current effects that we are using

You can only use cards on your turn.

If you discover a card then you can use _next_ turn

| Bonus | Effect   |   Count |
|---|---|---|
| Extra Ammo  | Hold onto this card, when you decide to use it during combat, then you can attack twice |  2 |
| Artillery Strike  | Pick any enemy unit to take on health away from  |  2 |
| Boost (aka Haul Ass)  | Move twice with the unit that discovered this bonus|  2 |
| Survivors Found  | Add health back to the unit that discovered this. +2 Infantry/Rockets OR +1 Mech |  2 |

**Pull request merged**
